/*
 * execsnoop.c — userspace loader and event printer, Chapter 7
 *
 * The skeleton (execsnoop.skel.h, generated by bpftool at build time) wraps
 * open/load/attach/destroy into typed C functions so there is no stringly-
 * typed map lookup or fd juggling:
 *
 *   execsnoop_bpf__open_and_load()  → verifies + loads BPF object
 *   execsnoop_bpf__attach()         → pins the tracepoint
 *   skel->maps.events               → the ring buffer map fd, by name
 *   execsnoop_bpf__destroy()        → detaches + unloads + frees
 *
 * Build:  make  (no sudo needed)
 * Run:    sudo ./execsnoop
 */
#include <stdio.h>
#include <signal.h>
#include <errno.h>
#include <bpf/libbpf.h>
#include "execsnoop.skel.h"
#include "execsnoop.h"

static volatile int stop;

static void on_signal(int sig) { stop = 1; }

static int handle_event(void *ctx, void *data, size_t len)
{
	const struct event *e = data;
	printf("%-8u %-6u %-16s %s\n", e->pid, e->uid, e->comm, e->filename);
	return 0;
}

int main(void)
{
	struct execsnoop_bpf *skel;
	struct ring_buffer   *rb;
	int err;

	/* Suppress libbpf's verbose debug messages. */
	libbpf_set_print(NULL);

	/* Open + verify + load the BPF object (pre-compiled, not JIT'd here). */
	skel = execsnoop_bpf__open_and_load();
	if (!skel) {
		fprintf(stderr, "Failed to open/load BPF skeleton\n");
		return 1;
	}

	/* Pin the tracepoint. */
	err = execsnoop_bpf__attach(skel);
	if (err) {
		fprintf(stderr, "Failed to attach: %d\n", err);
		goto cleanup;
	}

	/* Connect the ring buffer to our callback. */
	rb = ring_buffer__new(bpf_map__fd(skel->maps.events),
			      handle_event, NULL, NULL);
	if (!rb) {
		fprintf(stderr, "Failed to create ring buffer\n");
		err = 1;
		goto cleanup;
	}

	signal(SIGINT,  on_signal);
	signal(SIGTERM, on_signal);

	printf("%-8s %-6s %-16s %s\n", "PID", "UID", "COMM", "FILENAME");
	printf("%.70s\n",
	       "----------------------------------------------------------------------");

	while (!stop) {
		/* Poll with a 100 ms timeout so we check `stop` regularly. */
		err = ring_buffer__poll(rb, 100);
		if (err == -EINTR) { err = 0; break; }
		if (err < 0) {
			fprintf(stderr, "ring_buffer__poll: %d\n", err);
			break;
		}
	}

	printf("\nDetached. Bye!\n");
	ring_buffer__free(rb);
cleanup:
	execsnoop_bpf__destroy(skel);
	return err < 0 ? 1 : 0;
}
